# Start with the node 16 base image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy over the package.json and yarn.lock files
COPY package*.json ./

# Install dependencies with Yarn
RUN yarn install

# Copy over the rest of the project
COPY . .

# Build the project
RUN yarn build

# Expose the desired port
EXPOSE $PORT

EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD extra/healthcheck
ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
CMD ["node", "server/server.js"]