version: '3.8'

services:
  uptime-kuma:
    build: .
    image: tom/uptime-kuma
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "docker-entrypoint.sh & sleep 10 && mysql -uroot -p${DB_PASSWORD} ${DB_NAME} < /docker-entrypoint-initdb.d/grant.sql"
      ]

volumes:
  uptime-kuma-data:
  db-data:
