SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET GLOBAL innodb_flush_log_at_trx_commit = 2;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- GRANT SUPER ON *.* TO 'kuma_manager'@'%';
-- FLUSH PRIVILEGES;