-- You should not modify if this have pushed to Github, unless it does serious wrong with the db.
START TRANSACTION;

-- Generated by Intellij IDEA
CREATE TABLE setting_dg_tmp (
    id INT PRIMARY KEY AUTO_INCREMENT,
    `key` VARCHAR(200) NOT NULL UNIQUE,
    value TEXT,
    type VARCHAR(20)
);

INSERT INTO setting_dg_tmp (id, `key`, value, type)
SELECT id, `key`, value, type
FROM setting;

DROP TABLE setting;

ALTER TABLE setting_dg_tmp RENAME TO setting;

COMMIT;
